version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.3
    working_directory: ~/tmp
    steps:
      - checkout
      - run: npm install
      - run: NODE_ENV=development npm install --prefix client 
      - run: npm run build --prefix client

  deployment:
  staging:
    branch: master
    heroku:
      appname: whispering-dawn-16868

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deployment
          requires:
            - build
          filters:
            branches:
              only: master